services:
    t73_biz_form_conductor.conductor:
        class: T73Biz\Bundle\FormConductorBundle\Service\Conductor
        arguments: 
            - %t73_biz_form_conductor.access_token%
            - %t73_biz_form_conductor.base_uri%